language: bash

install:
  # Install a custom version of shellcheck instead of Travis CI's default
  - scversion=latest
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-${scversion}.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-${scversion}/shellcheck" "$@"; }

script: shellcheck kiss
